### ISSUE TITLE
Configure soft serve

### ISSUE THREAD

**Issue by daviroo** [Extheoisah/hxckr-infra#2]
- [x] 1. Setup Git Service Interface:

- Define the interface for the Git service, outlining the methods that will be required (clone_repo, push_changes, commit_changes).

- [x] 2. Implement Repository Cloning:

- Implement the logic for cloning a repository from a remote source to a local directory on the server.
- Ensure the cloned repository is properly configured for further operations.

- [x] 3. Handle Pulling and Pushing Changes:

- Implement methods to pull the latest changes from the remote repository.
- Implement methods to push local changes back to the remote repository.
- Handle potential merge conflicts during pull/push operations.

- [x] 4. Error Handling and Logging:

- Implement robust error handling for all Git operations, ensuring that failures are logged and reported appropriately.
- Ensure that users receive meaningful error messages if a Git operation fails.

**Comment by nully0x** [comment]
@daviroo please review this issue with what we want to archive with soft serve, I think 4,5 and 6 should be a separate issue.
